### ISSUE TITLE
[Bug] `ponder codegen` does not safely handle schema errors

### ISSUE THREAD

**Issue by 0xOlias** [0xOlias/ponder#175]

**Comment by Willyham** [comment]
An experience report on this:

When writing my GraphQL schema it was very difficult to understand issues, especially when the file was syntactically correct but not considered correct by ponder's rules (e.g. embedding a non-scalar non-entity type in an entity).

`codegen` completes with no error, and I had to look into the generated code to find that no entity structs were generated, and then work backwards and effectively bisect my changes manually to understand which part was causing the error to discover ponder's internal rules.

**Comment by 0xOlias** [comment]
Will be fixed by https://github.com/0xOlias/ponder/issues/348, which will overhaul the schema validation code path (and UX).
