### ISSUE TITLE
TypeError: abi.filter is not a function

### ISSUE THREAD

**Issue by shunkakinoki** [0xOlias/ponder#176]
Hi! Was keen to explore w/ ponder

I get this error when I initiate the project, any ideas for where this is from?

**Comment by shunkakinoki** [comment]
My bad, it was on bad abi

**Comment by 0xOlias** [comment]
Out of curiosity, what was wrong with it? Curious if it was it a hardhat-style ABI:

```json
{
  "contractName": "...",
  "abi": [{},{}]
}
```
because we could consider supporting those by default.

**Comment by shunkakinoki** [comment]
@0xOlias I missed this - ah the ABI was on a completely wrong path if i remember haha
