### ISSUE TITLE
`params` can be `undefined` if an indexed event has correct `topic[0]`, but wrong `topic[n]` and/or `data`

### ISSUE THREAD

**Issue by Gilgames000** [0xOlias/ponder#187]
The `params` object  when indexing an event can be `undefined` if an indexed event has correct `topic[0]`, but wrong `topic[n]` and/or `data`.

![image](https://github.com/0xOlias/ponder/assets/22778436/8b6703c9-e0da-4dbc-949d-9d712626c92e)

This can circumvented by checking whether `params` is `undefined` from within the handler, but it would be cool if ponder could handle it internally!

![image](https://github.com/0xOlias/ponder/assets/22778436/47971b74-60f5-4ec6-a732-5a25d76d4aaa)

**Comment by 0xOlias** [comment]
Hi @Gilgames000 - could you help me understand what scenario might cause this to happen? Thanks!

**Comment by Gilgames000** [comment]
Sure! The problem is that you could craft an event with a specific topic in the 0-th field alongside "incorrect" data fields and it will still get picked up as if it were indeed the correct event you're looking for because the selector is matching.

I encountered this on Avalanche when indexing all NFTs, there was this weird contract with some weird-ass Transfer event that ended up breaking the thing lol

**Comment by 0xOlias** [comment]
Got it, thanks for the clarification. This should be "fixed" in the sense that Ponder will fetch these events but "skip" them silently. Will consider adding a debug-level log whenever this happens, just for visibility.

Thanks for contributing!!
