### ISSUE TITLE
[Bug] Consider normalizing (lowercase) bytes values

### ISSUE THREAD

**Issue by holic** [0xOlias/ponder#194]
If I write bytes (address or otherwise), I would expect that querying for those wouldn't be impacted by checksummed bytes.

This could be done with `bytea` column type on postgres databases, but may need some finagling in sqlite

**Comment by 0xOlias** [comment]
So, you would expect that if you created an entity record like this:
```typescript
ponder.on("setup", async ({ context }) => {
  await context.entities.User.create({
    id: "",
    data: {
      byteField: "0xABC"
    },
  })
})
```

You would then be able to query for it using:
```graphql
{
  users(where: { byteField: "0xabc" }) {
    id
  }
}
```

Is that correct?

**Comment by holic** [comment]
Yep!

**Comment by 0xOlias** [comment]
Pasting another comment from Telegram on this issue:

> i'm running into some mild dx issues regarding normalized addresses — i've taken to using viem's getAddress to checksum all addresses that i'm using as object ids and when i query the api i ensure i use the normalized address as well. imo ponder should take a stance on whether addresses are normalized as checksummed or lowercase and ensure that all addresses my handlers see are in that format. then on the query side if there were an Address graphql type you could ensure that it's coerced into whatever the correct format is in the database, regardless of what the user passed in, since there's a semantic understanding that the checksummed and lowercased addresses should be equivalent

I responded with a suggestion for how to resolve:
1) add Address type in schema.graphql (new custom scalar)
2) make sure all EVM addresses are lowercase before passing into user land (eg an event param typed as solidity address). These are already typed using viem `Address which seems correct
3) GraphQL resolvers should convert any input values for fields typed as Address to lowercase (or throw validation error?)
4) Finally, the entity store API functions should apply validation or coercion to Address fields from schema.graphql. Should also type them as viem Address for clarity.
