### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'bySelector')

### ISSUE THREAD

**Issue by shrugs** [0xOlias/ponder#269]
caused by an empty `src/[anything].ts` file

https://github.com/0xOlias/ponder/blob/08434e975792a4babc195ae74839568b480a08ff/packages/core/src/event-aggregator/service.ts#L131

https://github.com/0xOlias/ponder/commit/1e5cb06e70b30ae15021bbdea0428ce40c5982ea#diff-5219fe2dcb7582ca6c2340767ca55e4b11dec5a6b8d49f80a1c4ab402954ea8eR149

which was introduced in 0.0.73

**Comment by 0xOlias** [comment]
Thanks for reporting! Not sure I follow  - I tried adding a file called `src/blah.ts` with no text to a ponder project, then ran the dev server, but not seeing this error. Could you be more specific on how to repro this?

**Comment by shrugs** [comment]
ah sorry, my file has `import { ponder } from "@/generated";` at the top and that's it
