### ISSUE TITLE
[Feature] Encode BigInt as postgres numeric data type

### ISSUE THREAD

**Issue by kliyer-ai** [0xOlias/ponder#334]
This custom encoding that is currently used for `BigInt` makes working directly with the database a very painful experience.

How it looks:
![image](https://github.com/0xOlias/ponder/assets/27199575/45ef9098-db8c-4079-afb9-60fd584a1e9e)

How it should look:
![image](https://github.com/0xOlias/ponder/assets/27199575/24ef2b4c-9688-4a28-8fc2-cd017ae76876)

Numeric docs: https://www.postgresql.org/docs/current/datatype-numeric.html

**Comment by 0xOlias** [comment]
Fixed in #361. Note that direct database access is not done yet - still need to create the views.
