### ISSUE TITLE
[Feature] Convert codebase to ESM

### ISSUE THREAD

**Issue by o-az** [0xOlias/ponder#378]
- [x] `@ponder/core`,
- [x] `create-ponder`,
- [x] `examples/*`,
- [x] generated code,
- [x] verify all tests pass.

After this, Ponder will emit 100% ESM code.

**Comment by o-az** [comment]
Related to #364

**Comment by 0xOlias** [comment]
Done in https://github.com/0xOlias/ponder/pull/416
