### ISSUE TITLE
Handlers don't trigger properly on networks without baseFeePerGas

### ISSUE THREAD

**Issue by smartcontracts** [0xOlias/ponder#82]
Tried to use `ponder` to index some stuff on Optimism, which currently does not have `baseFeePerGas` on mainnet. Although this is being changed very soon, it currently causes `ponder` to silently break when using sqlite as the backend. One potential fix would be to make `baseFeePerGas` nullable or, alternatively, add in some default value in `parseBlock`. For now I'm hacking around this by having a default value of `0x0`.

**Comment by 0xOlias** [comment]
Nice find, I didn't know this about optimism. Was able to repro locally, and will add an optimism contract to the `examples` repo (had not done any testing on optimism).

SQLite errors are occasionally silent for some reason, have not gotten to the bottom of that yet.

I think adding a default of `0x0` to `baseFeePerGas` makes sense, will fix.

**Comment by 0xOlias** [comment]
Should be fixed in `@ponder/core@0.0.28` via https://github.com/0xOlias/ponder/commit/38e3dc51332386ffa205f867a7562488b20ea38b
