### ISSUE TITLE
Multi-tenant apps

### ISSUE THREAD

**Issue by holic** [0xOlias/ponder#93]
It'd be great if there was a pattern both in ponder's DB and ponder's GraphQL server that could support multi-tenant apps. My main use case is different chains/networks for the same app, to avoid having to pay for/spin up multiple databases and apps for each chain.

**Comment by 0xOlias** [comment]
The DB name collision bug associated with this issue was fixed in #109.

But, I'll leave this open for continued discussion around patterns for serving multiple ponder instances from the same HTTP server.

**Comment by 0xOlias** [comment]
Closing for now, may open a discussion for this sometime down the road.
