### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by 0xOlias** [0xOlias/ponder#96]
Could add a `with-docker` example project and perhaps a `--with-docker` option to `create-ponder` that autogenerates a Dockerfile

**Comment by roninjin10** [comment]
This might be a pretty light lift I can do sometime

**Comment by 0xOlias** [comment]
@roninjin10 would appreciate help! not a huge docker user myself.

**Comment by roninjin10** [comment]
Started a pr here https://github.com/0xOlias/ponder/pull/184

**Comment by 0xOlias** [comment]
Closed in https://github.com/0xOlias/ponder/pull/293
